// Code generated by protoc-gen-go. DO NOT EDIT.
// source: goget.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A job represents a download, provided with neccessary information
type Job struct {
	// The url of the resource to be downloaded
	Url string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	// The file path to be saved
	Path string `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	// Username for auth, such as ftp download, an account is always needed
	Username string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	// Password for auth
	Passwd string `protobuf:"bytes,4,opt,name=passwd" json:"passwd,omitempty"`
	// The cnt indicates the thread count for cocurrent downloading
	Cnt                  int64    `protobuf:"varint,5,opt,name=cnt" json:"cnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_goget_b63c75ef74bca686, []int{0}
}
func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (dst *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(dst, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Job) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Job) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Job) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *Job) GetCnt() int64 {
	if m != nil {
		return m.Cnt
	}
	return 0
}

type JobInfo struct {
	// The id of the job
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// The url of the resource to be downloaded
	Url string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	// The file path to be saved
	Path string `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
	// The cnt indicates the thread count for cocurrent downloading
	Cnt                  int64    `protobuf:"varint,4,opt,name=cnt" json:"cnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobInfo) Reset()         { *m = JobInfo{} }
func (m *JobInfo) String() string { return proto.CompactTextString(m) }
func (*JobInfo) ProtoMessage()    {}
func (*JobInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_goget_b63c75ef74bca686, []int{1}
}
func (m *JobInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobInfo.Unmarshal(m, b)
}
func (m *JobInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobInfo.Marshal(b, m, deterministic)
}
func (dst *JobInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobInfo.Merge(dst, src)
}
func (m *JobInfo) XXX_Size() int {
	return xxx_messageInfo_JobInfo.Size(m)
}
func (m *JobInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_JobInfo.DiscardUnknown(m)
}

var xxx_messageInfo_JobInfo proto.InternalMessageInfo

func (m *JobInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *JobInfo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *JobInfo) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *JobInfo) GetCnt() int64 {
	if m != nil {
		return m.Cnt
	}
	return 0
}

// A Id represent a specified job
type Id struct {
	// The string format of given uuid
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_goget_b63c75ef74bca686, []int{2}
}
func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (dst *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(dst, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

// A Stats consists of progress information for a specified job
type Stats struct {
	// The status of the job
	Status int64 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	// The data transport speed rate of the job
	Rate int64 `protobuf:"varint,2,opt,name=rate" json:"rate,omitempty"`
	// The downloading file size of the job.
	Size int64 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	// The number of bytes already been fetched.
	Done                 int64    `protobuf:"varint,4,opt,name=done" json:"done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stats) Reset()         { *m = Stats{} }
func (m *Stats) String() string { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()    {}
func (*Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_goget_b63c75ef74bca686, []int{3}
}
func (m *Stats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stats.Unmarshal(m, b)
}
func (m *Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stats.Marshal(b, m, deterministic)
}
func (dst *Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stats.Merge(dst, src)
}
func (m *Stats) XXX_Size() int {
	return xxx_messageInfo_Stats.Size(m)
}
func (m *Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_Stats proto.InternalMessageInfo

func (m *Stats) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Stats) GetRate() int64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *Stats) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Stats) GetDone() int64 {
	if m != nil {
		return m.Done
	}
	return 0
}

// A empty message means void
type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_goget_b63c75ef74bca686, []int{4}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Job)(nil), "api.Job")
	proto.RegisterType((*JobInfo)(nil), "api.JobInfo")
	proto.RegisterType((*Id)(nil), "api.Id")
	proto.RegisterType((*Stats)(nil), "api.Stats")
	proto.RegisterType((*Empty)(nil), "api.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GoGetClient is the client API for GoGet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoGetClient interface {
	// A simple RPC.
	//
	// Add a goget job.
	//
	Add(ctx context.Context, in *Job, opts ...grpc.CallOption) (*JobInfo, error)
	// A simple RPC.
	//
	// Get a goget job info.
	//
	Get(ctx context.Context, in *Id, opts ...grpc.CallOption) (*JobInfo, error)
	// A simple RPC.
	//
	// Add a goget job.
	//
	GetAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (GoGet_GetAllClient, error)
	// A server-to-client RPC.
	//
	// Obtains the Current job progress
	//
	Progress(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Stats, error)
	// A client-to-server RPC.
	//
	// Accepts a job id
	//
	Start(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Empty, error)
	// A client-to-server RPC.
	//
	// Accepts a job id
	//
	Stop(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Empty, error)
	// A client-to-server RPC.
	//
	// Accepts a job id
	//
	Delete(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Empty, error)
}

type goGetClient struct {
	cc *grpc.ClientConn
}

func NewGoGetClient(cc *grpc.ClientConn) GoGetClient {
	return &goGetClient{cc}
}

func (c *goGetClient) Add(ctx context.Context, in *Job, opts ...grpc.CallOption) (*JobInfo, error) {
	out := new(JobInfo)
	err := c.cc.Invoke(ctx, "/api.GoGet/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goGetClient) Get(ctx context.Context, in *Id, opts ...grpc.CallOption) (*JobInfo, error) {
	out := new(JobInfo)
	err := c.cc.Invoke(ctx, "/api.GoGet/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goGetClient) GetAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (GoGet_GetAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GoGet_serviceDesc.Streams[0], "/api.GoGet/GetAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &goGetGetAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GoGet_GetAllClient interface {
	Recv() (*JobInfo, error)
	grpc.ClientStream
}

type goGetGetAllClient struct {
	grpc.ClientStream
}

func (x *goGetGetAllClient) Recv() (*JobInfo, error) {
	m := new(JobInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *goGetClient) Progress(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Stats, error) {
	out := new(Stats)
	err := c.cc.Invoke(ctx, "/api.GoGet/Progress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goGetClient) Start(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.GoGet/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goGetClient) Stop(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.GoGet/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goGetClient) Delete(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.GoGet/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoGetServer is the server API for GoGet service.
type GoGetServer interface {
	// A simple RPC.
	//
	// Add a goget job.
	//
	Add(context.Context, *Job) (*JobInfo, error)
	// A simple RPC.
	//
	// Get a goget job info.
	//
	Get(context.Context, *Id) (*JobInfo, error)
	// A simple RPC.
	//
	// Add a goget job.
	//
	GetAll(*Empty, GoGet_GetAllServer) error
	// A server-to-client RPC.
	//
	// Obtains the Current job progress
	//
	Progress(context.Context, *Id) (*Stats, error)
	// A client-to-server RPC.
	//
	// Accepts a job id
	//
	Start(context.Context, *Id) (*Empty, error)
	// A client-to-server RPC.
	//
	// Accepts a job id
	//
	Stop(context.Context, *Id) (*Empty, error)
	// A client-to-server RPC.
	//
	// Accepts a job id
	//
	Delete(context.Context, *Id) (*Empty, error)
}

func RegisterGoGetServer(s *grpc.Server, srv GoGetServer) {
	s.RegisterService(&_GoGet_serviceDesc, srv)
}

func _GoGet_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Job)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoGetServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GoGet/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoGetServer).Add(ctx, req.(*Job))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoGet_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoGetServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GoGet/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoGetServer).Get(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoGet_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GoGetServer).GetAll(m, &goGetGetAllServer{stream})
}

type GoGet_GetAllServer interface {
	Send(*JobInfo) error
	grpc.ServerStream
}

type goGetGetAllServer struct {
	grpc.ServerStream
}

func (x *goGetGetAllServer) Send(m *JobInfo) error {
	return x.ServerStream.SendMsg(m)
}

func _GoGet_Progress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoGetServer).Progress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GoGet/Progress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoGetServer).Progress(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoGet_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoGetServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GoGet/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoGetServer).Start(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoGet_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoGetServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GoGet/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoGetServer).Stop(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoGet_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoGetServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GoGet/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoGetServer).Delete(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoGet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.GoGet",
	HandlerType: (*GoGetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _GoGet_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _GoGet_Get_Handler,
		},
		{
			MethodName: "Progress",
			Handler:    _GoGet_Progress_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _GoGet_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _GoGet_Stop_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _GoGet_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAll",
			Handler:       _GoGet_GetAll_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "goget.proto",
}

func init() { proto.RegisterFile("goget.proto", fileDescriptor_goget_b63c75ef74bca686) }

var fileDescriptor_goget_b63c75ef74bca686 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x6d, 0xb2, 0x49, 0x5a, 0x47, 0x11, 0xd9, 0x83, 0x84, 0x82, 0xb6, 0xe6, 0x20, 0x3d, 0x15,
	0xd1, 0x2f, 0x28, 0x28, 0xa5, 0x3d, 0x69, 0x7a, 0xf4, 0xb4, 0x71, 0xd7, 0x1a, 0x48, 0xb3, 0xeb,
	0xee, 0x04, 0xd1, 0xdf, 0xf6, 0x07, 0x64, 0xa7, 0x69, 0x2b, 0x2d, 0xbd, 0xbd, 0x79, 0x6f, 0xf6,
	0xbd, 0x79, 0xb0, 0x70, 0xba, 0xd4, 0x4b, 0x85, 0x63, 0x63, 0x35, 0x6a, 0xce, 0x84, 0x29, 0xb3,
	0x4f, 0x60, 0x73, 0x5d, 0xf0, 0x0b, 0x60, 0x8d, 0xad, 0xd2, 0x60, 0x18, 0x8c, 0x4e, 0x72, 0x0f,
	0x39, 0x87, 0xc8, 0x08, 0xfc, 0x48, 0x43, 0xa2, 0x08, 0xf3, 0x3e, 0xf4, 0x1a, 0xa7, 0x6c, 0x2d,
	0x56, 0x2a, 0x65, 0xc4, 0x6f, 0x67, 0x7e, 0x09, 0x89, 0x11, 0xce, 0x7d, 0xc9, 0x34, 0x22, 0xa5,
	0x9d, 0xbc, 0xf3, 0x5b, 0x8d, 0x69, 0x3c, 0x0c, 0x46, 0x2c, 0xf7, 0x30, 0x7b, 0x81, 0xee, 0x5c,
	0x17, 0xb3, 0xfa, 0x5d, 0xf3, 0x73, 0x08, 0x4b, 0xd9, 0xa6, 0x86, 0xa5, 0xdc, 0x9c, 0x11, 0x1e,
	0x9e, 0xc1, 0xfe, 0x9d, 0xd1, 0x5a, 0x46, 0x3b, 0xcb, 0x14, 0xc2, 0x99, 0xf4, 0xbb, 0x4d, 0xb3,
	0xf5, 0x23, 0x9c, 0xbd, 0x42, 0xbc, 0x40, 0x81, 0xce, 0xdf, 0xe7, 0x50, 0x60, 0xe3, 0x48, 0x66,
	0x79, 0x3b, 0xf9, 0x47, 0x56, 0xa0, 0xa2, 0x4c, 0x96, 0x13, 0xf6, 0x9c, 0x2b, 0x7f, 0xd6, 0x1d,
	0x59, 0x4e, 0xd8, 0x73, 0x52, 0xd7, 0xaa, 0x4d, 0x25, 0x9c, 0x75, 0x21, 0x7e, 0x5a, 0x19, 0xfc,
	0xbe, 0xff, 0x0d, 0x20, 0x9e, 0xea, 0xa9, 0x42, 0x3e, 0x00, 0x36, 0x91, 0x92, 0xf7, 0xc6, 0xc2,
	0x94, 0xe3, 0xb9, 0x2e, 0xfa, 0x67, 0x1b, 0xe4, 0x0b, 0x67, 0x1d, 0x7e, 0x0d, 0xcc, 0xef, 0x75,
	0x89, 0x9e, 0xc9, 0x03, 0xfd, 0x16, 0x92, 0xa9, 0xc2, 0x49, 0x55, 0x71, 0x20, 0x85, 0x02, 0xf6,
	0xb7, 0xee, 0x02, 0x7e, 0x03, 0xbd, 0x67, 0xab, 0x97, 0x56, 0x39, 0xb7, 0x33, 0x5b, 0x3f, 0xa1,
	0xc2, 0x14, 0xe5, 0xbb, 0x5b, 0xdc, 0xd7, 0xc9, 0x32, 0xeb, 0xf0, 0x2b, 0x88, 0x16, 0xa8, 0xcd,
	0x31, 0x79, 0x00, 0xc9, 0xa3, 0xaa, 0x14, 0xaa, 0x23, 0x0b, 0x45, 0x42, 0xff, 0xe8, 0xe1, 0x2f,
	0x00, 0x00, 0xff, 0xff, 0xf3, 0x3c, 0x9d, 0x79, 0x56, 0x02, 0x00, 0x00,
}
